### PR TITLE
Outputs updates

### PR DESCRIPTION
**Pull request by aeslaughter**

### CODE REVIEW

**Comment by adamLange** [comment]
Was I exodiffing not on the final timestep?

**Comment by aeslaughter** [comment]
I did not run the tests, I just execute my script that updates input files. The old default for MOOSE was NOT to execute on initial, so your tests to not output the initial condition. To keep this behavior, now that initial output is on by default, it to explicitly use the "execute_on" and limit it to 'timestep_end'

**Comment by adamLange** [comment]
Ok, thank you sir!

**Comment by adamLange** [comment]
Hmm... simpleDiffusion test is failing...

kernels/simple_diffusion.test:    *****************************************************************
kernels/simple_diffusion.test:               EXODIFF    (Version: 2.69) Modified: 2013-07-11
kernels/simple_diffusion.test:               Authors:  Richard Drake, rrdrake@sandia.gov  
kernels/simple_diffusion.test:                         Greg Sjaardema, gdsjaar@sandia.gov  
kernels/simple_diffusion.test:               Run on    2015/09/21   11:58:58 CDT
kernels/simple_diffusion.test:    *****************************************************************
kernels/simple_diffusion.test: 
kernels/simple_diffusion.test: Reading first file ... 
kernels/simple_diffusion.test: Reading second file ... 
kernels/simple_diffusion.test:   FILE 1: /home/adam/projects/slug/tests/kernels/simple_diffusion/gold/simple_diffusion_out.e
kernels/simple_diffusion.test:    Title: simple_diffusion_test_out.e
kernels/simple_diffusion.test:           Dim = 2, Blocks = 1, Nodes = 121, Elements = 100, Nodesets = 4, Sidesets = 4
kernels/simple_diffusion.test:           Vars: Global = 0, Nodal = 1, Element = 0, Nodeset = 0, Sideset = 0, Times = 2
kernels/simple_diffusion.test: 
kernels/simple_diffusion.test:   FILE 2: /home/adam/projects/slug/tests/kernels/simple_diffusion/simple_diffusion_out.e
kernels/simple_diffusion.test:    Title: simple_diffusion_out.e
kernels/simple_diffusion.test:           Dim = 2, Blocks = 1, Nodes = 121, Elements = 100, Nodesets = 4, Sidesets = 4
kernels/simple_diffusion.test:           Vars: Global = 0, Nodal = 1, Element = 0, Nodeset = 0, Sideset = 0, Times = 1
kernels/simple_diffusion.test: 
kernels/simple_diffusion.test: exodiff: WARNING First file has 2 result times while the second file has 1.
kernels/simple_diffusion.test: 
kernels/simple_diffusion.test: exodiff: INFO .. Map option is not needed.
kernels/simple_diffusion.test: exodiff: WARNING First file has 2 result times while the second file has 1.
kernels/simple_diffusion.test: 
kernels/simple_diffusion.test: Coordinates will be compared .. tol:    1e-06 (absolute), floor:        0
kernels/simple_diffusion.test: Coordinates will be compared .. tol:    1e-06 (absolute), floor:        0
kernels/simple_diffusion.test: Time step values will be compared .. tol:  5.5e-06 (relative), floor:    1e-10
kernels/simple_diffusion.test: No Global variables on either file.
kernels/simple_diffusion.test: Nodal variables to be compared:
kernels/simple_diffusion.test:  u                                tol:  5.5e-06 (relative), floor:    1e-10
kernels/simple_diffusion.test: No Element variables on either file.
kernels/simple_diffusion.test: No Element Attribute variables on either file.
kernels/simple_diffusion.test: No Nodeset variables on either file.
kernels/simple_diffusion.test: No Sideset variables on either file.
kernels/simple_diffusion.test: 
kernels/simple_diffusion.test:   ==============================================================
kernels/simple_diffusion.test:   NOTE: All node and element ids are reported as global ids.
kernels/simple_diffusion.test: 
kernels/simple_diffusion.test:   --------- Time step 1, 0.0000000e+00 ~ 1.0000000e+00, rel diff: -1.00000e+00 (FAILED) 
kernels/simple_diffusion.test: Nodal variables:
kernels/simple_diffusion.test:    u  rel diff:  0.0000000e+00 ~  1.0000000e-01 = 1.00000e+00 (node 2)
kernels/simple_diffusion.test: 
kernels/simple_diffusion.test: exodiff: Files are different
kernels/simple_diffusion.test:  
kernels/simple_diffusion.test............................................................... FAILED (EXODIFF) (reprint)

## Final Test Results:

kernels/CompressibleReynoldsPressure.test................................................................. OK

## kernels/simple_diffusion.test............................................................... FAILED (EXODIFF)

**Comment by aeslaughter** [comment]
This test should have the "initial" condition, notice the number of Times
reported by each file. Just remove the execute_on from the input file. This
is a failure of mine when updating.

**Pull request merged**
